### PR TITLE
Make ux better and provide easier python module install

### PR DESCRIPTION
**Pull request by streamableW**
image

made the ui better, made ban logging more efficient and easier while also making the python install easier.

### CODE REVIEW

**Comment by SurvivorJosh** [comment]
Yo in the future wanna make a tool together? I’m bad at making tools look good

**Comment by streamableW** [comment]
> Yo in the future wanna make a tool together? I’m bad at making tools look good

sure

**Comment by streamableW** [comment]
> Yo in the future wanna make a tool together? I’m bad at making tools look good

lithium#8140

**Comment by streamableW** [comment]
dude did u forget? also my new tag is xki#8140

**Pull request merged**
